version: "3.8"
services:
  mysql:
    image: mysql:8.0
    user: 501:20
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - net
    env_file:
      - configs/mysql.env
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./deployment/migrations:/docker-entrypoint-initdb.d
    container_name: mini-aspire-mysql

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 173.0.0.0/16
